/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mad' at '13.06.16 11:24' with Gradle 2.13
 *
 * @author mad, @date 13.06.16 11:24
 */
public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
